//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaySpec1 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class noparallel : global::System.Configuration.ApplicationSettingsBase {
        
        private static noparallel defaultInstance = ((noparallel)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new noparallel())));
        
        public static noparallel Default {
            get {
                return defaultInstance;
            }
        }
    }
}
