name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.0'

      - name: Install dependencies
        run: dotnet restore

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test Category=yoptest --configuration Release --no-build --logger:trx
